name: Build and upload to PyPI
on: 
 push:
 pull_request:
 release:
   types: [published]

jobs:
  build_artifacts:
    name: Build artifacts
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: Fetch full git history
        run: git fetch --prune --unshallow
      - name: Set up Conda env
        uses: mamba-org/setup-micromamba@db1df3ba9e07ea86f759e98b575c002747e9e757
        with:
          environment-file: environment.yml
          cache-environment: true
      - shell: bash -el {0}
        run:
          python -m build
      - uses: pypa/gh-action-pypi-publish@v1.8.11
        if: github.event_name == 'release'
        with:
          user: __token__
          password: ${{ secrets.PYPI_RELEASE_TOKEN }}
